package com.example.gymbuddy;

import java.util.ArrayList;

public class RecordsInitiatior {

    public ArrayList<Exercise> getExerciseRecords(){
            ArrayList<Exercise> recs = new ArrayList<>();
            // Chest exercises
            recs.add(new Exercise(-1, "Bench Press", 10, "The bench press is a classic and fundamental strength training exercise that targets the muscles of the chest, shoulders, and triceps. Typically performed on a flat weight bench, the exercise involves lifting a barbell loaded with weights from a starting position at chest level and extending the arms upward until they are fully extended. This compound movement not only helps build upper body strength but also engages stabilizing muscles throughout the torso. The bench press is a popular choice for those looking to develop chest muscles and enhance overall upper body power. It is a versatile exercise that can be adapted for various fitness levels by adjusting the weight and grip width.", R.drawable.bench_press));
            recs.add(new Exercise(-1, "Push ups", 10, "Push-ups are a classic bodyweight exercise that effectively targets the chest, shoulders, triceps, and core muscles. In this exercise, you start in a plank position with your hands placed slightly wider than shoulder-width apart. Lower your body by bending your elbows until your chest nearly touches the ground, then push back up to the starting position, keeping your body in a straight line throughout. Push-ups not only build upper body strength but also engage the muscles of the core for stability. This versatile and accessible exercise can be modified to suit various fitness levels and is an excellent addition to any home or gym workout routine.", R.drawable.pushups));
            recs.add(new Exercise(-1, "Dips", 13, "Dips are a compound bodyweight exercise that primarily targets the triceps, chest, and shoulders. To perform dips, you position yourself between parallel bars, dipping handles, or any sturdy elevated surfaces with your hands gripping the supports. Lower your body by bending your elbows until your shoulders are below your elbows, then push yourself back up to the starting position. Dips engage the upper body muscles and also involve the chest and shoulders, providing an effective workout for building strength and muscular endurance.", R.drawable.dips));
            recs.add(new Exercise(-1, "Dumbbell flies", 10, "Dumbbell flies, a chest isolation exercise, are executed by lying on a bench with a dumbbell in each hand, arms extended above the chest. With a slight bend in the elbows, the dumbbells are lowered in a controlled motion out to the sides, creating a gentle stretch in the chest. Exhaling, the weights are then squeezed back to the starting position, emphasizing chest muscle contraction. This exercise is effective for enhancing chest muscle definition and shoulder joint flexibility. To maximize benefits and minimize the risk of injury, it's crucial to use an appropriate weight, maintain proper form, and perform the movement with deliberate control.", R.drawable.dumbell_flies));

            // Back exercises
            recs.add(new Exercise(-1, "Back extensions", 23, "Back extensions are a targeted exercise that focuses on strengthening the muscles of the lower back and glutes. Typically performed on a back extension apparatus or Roman chair. Back extensions involve positioning yourself face down on the apparatus with your hips resting against the padded support and your feet secured. Cross your arms over your chest or place your hands behind your head. Lower your upper body toward the floor by hinging at your hips while keeping your spine in a neutral position. Engage your lower back and glutes to lift your torso back up to a horizontal position, creating a straight line from your head to your heels. This controlled movement targets the erector spinae muscles along the spine, promoting lower back strength and stability. Back extensions are an effective way to enhance core strength and minimize the risk of lower back discomfort.", R.drawable.back_extensions));
            recs.add(new Exercise(-1, "Barbell row", 21, "The barbell row is a compound exercise that targets the muscles of the upper back, particularly the latissimus dorsi, rhomboids, and traps. To perform a barbell row, one typically stands with feet shoulder-width apart, bends at the hips to bring the torso parallel to the ground, and grips a barbell with hands slightly wider than shoulder-width. Keeping the back straight and core engaged, the barbell is pulled towards the lower chest or upper abdomen, focusing on squeezing the shoulder blades together. The movement is then controlled as the barbell is lowered back down. Barbell rows are effective for building upper back strength and promoting better posture. It's essential to prioritize proper form, maintain a neutral spine, and gradually increase weight to optimize the benefits of this exercise while minimizing the risk of injury.", R.drawable.barbellrow));
            recs.add(new Exercise(-1, "Lat pulldown", 22, "The lat pulldown is a compound exercise that primarily targets the muscles of the upper back, particularly the latissimus dorsi. To perform a lat pulldown, one sits at a cable machine with a wide grip attachment. Grasping the bar overhead, the arms are extended, and the torso remains upright. Pulling the bar down towards the chest, the shoulder blades are squeezed together at the bottom of the movement before allowing the bar to return to the starting position with controlled resistance. Lat pulldowns are effective for building strength and definition in the upper back, promoting better posture, and engaging the lats. It is crucial to maintain a stable position, avoid excessive swinging, and use an appropriate weight to ensure proper muscle engagement while minimizing the risk of injury.", R.drawable.lat_pulldown));
            recs.add(new Exercise(-1, "Pull ups", 22, "Pull-ups are a compound bodyweight exercise renowned for targeting the muscles of the upper body, particularly the latissimus dorsi, biceps, and upper back. To perform a pull-up, hang from a horizontal bar with an overhand grip, hands slightly wider than shoulder-width apart. Engage your shoulder blades and pull your body upward until your chin clears the bar. Lower your body back down with control, maintaining a straight line from head to heels. Pull-ups are effective for building upper body strength, enhancing grip, and promoting overall back development. Progressions and variations, such as assisted pull-ups or wide grip pull-ups, can be implemented to accommodate different fitness levels. Proper form, controlled movements, and gradual progression in intensity are crucial to maximizing the benefits of pull-ups while minimizing the risk of injury.", R.drawable.pullups));

            // Shoulder exercises
            recs.add(new Exercise(-1, "Face pull ups", 33, "Face pulls are a beneficial isolation exercise for the upper back and shoulders. Using a cable machine with a rope attachment, set the pulley at head height. Stand facing the machine, grasp the rope with an overhand grip, and step back. Pull the rope towards your face, keeping your upper arms parallel to the ground, and retract your shoulder blades. This movement targets the rear deltoids, traps, and upper back, promoting shoulder health and overall upper body stability.", R.drawable.cable_row_rear_delts));
            recs.add(new Exercise(-1, "Lateral raises", 32, "Lateral raises are a targeted shoulder exercise designed to isolate and strengthen the lateral or side deltoid muscles. Typically performed with dumbbells, one stands with feet shoulder-width apart, holding a dumbbell in each hand at their sides. With a slight bend in the elbows, the weights are lifted laterally away from the body until they reach shoulder height. Lateral raises emphasize the deltoids' outer portion, contributing to broader and more defined shoulders. It's crucial to execute this movement with controlled and deliberate motions, avoiding excessive swinging or using momentum. Adjusting the weight to a manageable level and focusing on proper form ensures the effectiveness of lateral raises while minimizing strain on the shoulder joints. ", R.drawable.lateral_raises));
            recs.add(new Exercise(-1, "Reverse flies", 33, "Reverse flies are a targeted exercise that primarily engages the muscles of the upper back, especially the rear deltoids and the trapezius. To perform reverse flies, start by standing or lying face down on an incline bench with a dumbbell in each hand, arms hanging straight down toward the floor. Keeping a slight bend in your elbows, exhale as you lift the weights out to the sides until your arms are parallel to the ground, squeezing your shoulder blades together at the top of the movement. Inhale as you lower the weights back down with control. Reverse flies contribute to improved shoulder and upper back definition, and they are valuable for balancing overall shoulder development. Maintaining proper form, using an appropriate weight, and executing the movement with control are essential for maximizing the benefits of reverse flies while minimizing the risk of injury.", R.drawable.reversefly));
            recs.add(new Exercise(-1, "Shoulder press", 30, "Shoulder presses, also known as overhead presses, are a fundamental upper body exercise targeting the deltoid muscles of the shoulders. To perform a shoulder press, start with a barbell or dumbbells at shoulder height, palms facing forward. Press the weight overhead by extending your arms until they are fully extended, then lower the weight back to the starting position with control. The movement can be done while sitting or standing. Shoulder presses contribute to building shoulder strength, improving overall upper body definition, and enhancing shoulder stability. It is crucial to maintain proper form, engage the core for stability, and use an appropriate weight to prevent strain.", R.drawable.shoulder_press));

            // Arms exercises
            recs.add(new Exercise(-1, "Bicep curls", 41, "Bicep curls are a fundamental isolation exercise aimed at developing the muscles of the biceps. Stand with feet shoulder-width apart, grasp a dumbbell in each hand or use a barbell with palms facing forward. With elbows close to the torso, exhale as you curl the weights upward, contracting the biceps at shoulder level. Hold briefly, then inhale as you lower the weights back down with controlled movements, avoiding any swinging. This classic exercise can be performed with various grips and equipment, contributing to improved bicep strength, size, and definition when incorporated into a well-rounded workout routine. Focus on maintaining proper form and using an appropriate weight to maximize effectiveness and reduce the risk of injury.", R.drawable.bicep_curls));
            recs.add(new Exercise(-1, "Hammer curls", 41, "Hammer curls are a bicep exercise that provides a unique twist by targeting the brachialis muscle in addition to the standard bicep engagement. To perform hammer curls, one stands with a dumbbell in each hand, palms facing the torso, and arms fully extended. Keeping the elbows close to the body, the weights are lifted towards the shoulders in a controlled manner, with the palms remaining in a neutral or \"hammer\" grip throughout the movement. This exercise not only contributes to overall bicep development but also strengthens the brachialis, enhancing arm aesthetics and functionality. Proper form, a controlled tempo, and a focus on the contraction at the top of the movement are key aspects to ensure the effectiveness of hammer curls while minimizing the risk of injury.", R.drawable.hammer_curls));
            recs.add(new Exercise(-1, "Tricep extensions", 42, "Tricep extensions, also known as tricep press or tricep pushdown, are isolation exercises that target the triceps muscles at the back of the upper arms. Using a cable machine or resistance band, stand with feet shoulder-width apart and grasp the cable or band with an overhand grip. Keep your elbows close to your body as you extend your arms downward, fully straightening them. Focus on contracting the triceps at the bottom of the movement before returning to the starting position with control. Tricep extensions are effective for building tricep strength and definition. It's crucial to maintain proper form, engage the core for stability, and use an appropriate resistance level to optimize the benefits of this exercise while minimizing the risk of injury.", R.drawable.tricep_extension));
            recs.add(new Exercise(-1, "Tricep rope", 41, "Tricep rope extensions, also known as tricep pushdowns with a rope attachment, are a targeted isolation exercise designed to engage and strengthen the triceps muscles. Stand facing a cable machine with a rope attachment connected to the high pulley. Grasp the ends of the rope with an overhand grip, keeping your elbows close to your sides. Extend your arms downward, fully straightening them and focusing on contracting the triceps at the bottom of the movement. Hold briefly before returning to the starting position with controlled resistance. Tricep rope extensions effectively target the triceps, emphasizing the lateral head of the muscle. It's essential to maintain proper form, control the movement, and use an appropriate weight to maximize benefits while minimizing the risk of injury.", R.drawable.tricep_rope));
            recs.add(new Exercise(-1, "Wrist curls", 43, "Wrist curls are a simple yet effective isolation exercise that targets the muscles of the forearm, specifically the flexor muscles. To perform wrist curls, sit or stand with a dumbbell in each hand, palms facing up, and your forearms resting on a flat surface. Allow your wrists to hang over the edge, and then curl the weights upward by flexing your wrists. Lift the weights as high as comfortably possible and then lower them back down with control. Wrist curls help improve forearm strength and endurance, which can be beneficial for various activities that involve grip strength. It's important to use an appropriate weight, maintain proper form, and perform the exercise with controlled movements to avoid strain on the wrists.", R.drawable.wrist_curls));

            // Legs exercises
            recs.add(new Exercise(-1, "Calf raises", 64, "Calf raises, a straightforward yet effective exercise, target the muscles in the calves. Stand with feet hip-width apart, lift your heels off the ground by pushing through the balls of your feet, and rise as high as possible on your toes. Holding the raised position briefly, feel the contraction in your calf muscles before slowly lowering your heels back down. Whether done on a flat surface or an elevated one for increased range of motion, calf raises strengthen the gastrocnemius and soleus muscles, contributing to enhanced lower leg strength and stability. Including calf raises in your workout routine can promote overall lower body strength and balance.", R.drawable.calf_raises));
            recs.add(new Exercise(-1, "Deadlifts", 61, "Deadlifts stand as a foundational compound exercise renowned for engaging various muscle groups, including the hamstrings, glutes, lower back, and core. Executing a conventional deadlift involves maintaining a neutral spine, bending at the hips and knees to grasp the barbell, and lifting it by straightening the hips and knees simultaneously. This movement not only enhances overall strength but also contributes to improved posture and functional fitness. It's crucial to prioritize proper form and gradual progression in weight to maximize the benefits while minimizing the risk of injury.", R.drawable.deadlifts));
            recs.add(new Exercise(-1, "Hip thrust", 61, "The hip thrust is a highly effective glute-targeting exercise designed to enhance hip extension strength and shape the muscles of the posterior chain. To perform a hip thrust, one typically sits on the floor with their upper back against a bench, places a barbell across their hips, and positions their feet flat on the ground. Engaging the glutes, the hips are then lifted towards the ceiling until the thighs are parallel to the ground. This movement emphasizes a strong contraction at the top of the lift. Hip thrusts are valuable for building gluteal strength and improving hip stability. Ensuring proper alignment, using an appropriate weight, and focusing on the glute squeeze during the lift are crucial elements for maximizing the effectiveness of hip thrusts and minimizing the risk of injury.", R.drawable.hip_thrust));
            recs.add(new Exercise(-1, "Leg curls", 63, "Leg curls are a targeted isolation exercise primarily focusing on the muscles of the hamstrings, located at the back of the thigh. To perform leg curls, one typically lies face down on a leg curl machine with the ankles secured under a padded lever. Starting with the legs fully extended, the exerciser curls the legs upward by flexing at the knees, bringing the heels towards the buttocks. The emphasis is on contracting the hamstrings throughout the movement. Leg curls contribute to hamstring strength, stability, and muscle definition. It's essential to execute the exercise with controlled movements, maintaining proper form to ensure effective muscle engagement and reduce the risk of strain.", R.drawable.leg_curls));
            recs.add(new Exercise(-1, "Lunges", 60, "Lunges are a versatile and effective lower body exercise that targets the quadriceps, hamstrings, glutes, and calves. To perform lunges, start by standing with feet together, then step forward with one foot, bending both knees to lower the body towards the ground. The back knee should hover just above the floor, and the front knee should be directly above the ankle. Push off the front foot to return to the starting position, and then repeat on the other leg. Lunges can be performed in various directions, including forward lunges, reverse lunges, and lateral lunges, offering a dynamic workout that enhances lower body strength, balance, and flexibility. It's crucial to maintain proper form, with the torso upright and core engaged, to optimize the benefits of lunges and reduce the risk of injury.", R.drawable.lunges));
            recs.add(new Exercise(-1, "Split squat", 60, "The split squat is a single-leg strength exercise that targets the muscles of the lower body, including the quadriceps, hamstrings, and glutes. To perform a split squat, start in a lunge position with one foot forward and the other foot positioned back on the toes. Lower your body by bending both knees, ensuring the front knee is directly above the ankle and the back knee hovers just above the ground. Keep the torso upright and engage the core for stability. Push through the heel of the front foot to return to the starting position. Split squats help improve unilateral strength, balance, and flexibility. It's crucial to maintain proper form, control the descent and ascent, and ensure both knees are aligned to optimize the benefits of this exercise while minimizing the risk of injury.", R.drawable.split_squats));
            recs.add(new Exercise(-1, "Squats", 60, "Squats are a fundamental and compound lower body exercise that targets multiple muscle groups, including the quadriceps, hamstrings, glutes, and lower back. To perform a squat, start with your feet shoulder-width apart, chest up, and core engaged. Lower your body by bending your knees and hips, as if sitting back into an imaginary chair, while keeping your back straight. Ensure that your knees are aligned with your toes and do not extend beyond them. Descend until your thighs are parallel to the ground or as far as your flexibility allows. Push through your heels to return to the starting position. Squats are highly effective for building leg strength, enhancing overall lower body development, and promoting functional fitness. It is crucial to prioritize proper form, control the movement, and gradually increase weight to maximize benefits and reduce the risk of injury. Including squats in a comprehensive strength training routine can contribute to improved muscle tone, power, and athletic performance.", R.drawable.squats));
            recs.add(new Exercise(-1, "Step ups", 60, "Step-ups are a lower body exercise that primarily targets the quadriceps, hamstrings, and glutes while also engaging the calves and core muscles. To perform step-ups, stand facing a sturdy bench or platform. Step onto the bench with one foot, ensuring your entire foot is on the surface. Push through the heel of the elevated foot to lift your body up onto the bench. Bring the opposite knee up towards your chest, and then lower it back down. Step back down with control, and repeat the movement, alternating legs. Step-ups are effective for building lower body strength, improving balance, and enhancing stability. It's important to maintain proper form, control the movement, and choose an appropriate bench height.", R.drawable.stepups));

            // Abs exercises
            recs.add(new Exercise(-1, "Crunches", 51, "Crunches, a widely practiced abdominal exercise, involve lying on your back with knees bent and hands behind your head. Engaging your abdominal muscles, exhale as you lift your head, neck, and shoulders off the ground, directing your ribcage towards your pelvis. The primary focus is on strengthening the rectus abdominis, commonly referred to as the \"six-pack\" muscles. It's crucial to perform crunches with proper form, avoiding neck strain and ensuring controlled movements during both the contraction and release phases. Incorporating a mix of core exercises in your routine can contribute to comprehensive abdominal strength and stability.", R.drawable.crunches));
            recs.add(new Exercise(-1, "Hanging legs raises", 52, "Hanging leg raises are a potent abdominal exercise that primarily targets the lower abdominal muscles. Executed by hanging from a pull-up bar or similar apparatus, one lifts their legs upward while keeping them straight until they are parallel to the ground or higher. This movement requires engaging the core to lift the legs and emphasizes controlled lowering to maximize muscle engagement. Hanging leg raises are effective for developing core strength, particularly targeting the rectus abdominis and hip flexors. Maintaining stability in the upper body and executing the exercise with deliberate control are essential for optimal results and to minimize strain on the lower back.", R.drawable.hanging_leg_raises));
            recs.add(new Exercise(-1, "Knee to elbow crunches", 53, "Knee to elbow crunches are a dynamic core exercise that combines the traditional crunch movement with a diagonal twist, engaging both the upper and lower abdominal muscles. To perform knee to elbow crunches, one lies on their back with hands behind the head, elbows wide, and legs lifted off the ground. As you crunch upward, simultaneously bring one knee toward the opposite elbow, creating a diagonal movement pattern. This exercise intensifies the contraction in the obliques and challenges the core's rotational strength. Maintaining a controlled tempo and ensuring the elbow and knee meet at the top of the movement are key to maximizing effectiveness.", R.drawable.knee_to_elbow_crunches));
            recs.add(new Exercise(-1, "Mountain climbers", 50, "Mountain climbers are a dynamic and full-body exercise that engages the core, shoulders, and legs while promoting cardiovascular fitness. To perform mountain climbers, start in a plank position with your hands directly beneath your shoulders and your body forming a straight line from head to heels. Alternate bringing your knees towards your chest in a rapid, running-like motion while maintaining the plank position. The exercise creates a continuous and rhythmic movement, simulating climbing. Mountain climbers are effective for improving core strength, enhancing endurance, and elevating heart rate. It's crucial to maintain a stable plank position, engage the core muscles, and perform the movement with control to maximize benefits and minimize the risk of strain. Incorporating mountain climbers into a high-intensity interval training (HIIT) routine or as part of a comprehensive bodyweight workout can provide a challenging and effective fitness experience.", R.drawable.mountain_climbers));
            recs.add(new Exercise(-1, "Plank", 50, "The plank is a fundamental core exercise that targets the muscles of the abdominals, lower back, and stabilizing muscles. To perform a plank, begin in a forearm plank position with your elbows directly beneath your shoulders, and your body forming a straight line from head to heels. Engage your core muscles, keeping your back flat, and hold the position for a predetermined amount of time. The plank is effective for building core strength, improving posture, and enhancing overall stability. It's essential to maintain proper alignment, avoid sagging or lifting the hips, and breathe steadily throughout the exercise. Planks can be adapted for different fitness levels by adjusting the duration and incorporating variations such as side planks or plank rotations.", R.drawable.plank));
            recs.add(new Exercise(-1, "Reverse crunches", 52, "Reverse crunches are a targeted abdominal exercise designed to engage the lower abdominal muscles. To perform reverse crunches, lie on your back with your hands placed beside you or under your hips for support. Lift your legs off the ground, bending your knees at a 90-degree angle. Exhale as you contract your lower abs, bringing your knees towards your chest, lifting your hips off the ground. Inhale as you lower your legs back down without letting them touch the floor. Reverse crunches effectively isolate the lower portion of the rectus abdominis and contribute to overall core strength. It's crucial to execute the movement with control, avoiding any swinging or momentum, to maximize engagement of the targeted muscles and minimize stress on the lower back. ", R.drawable.reverse_crunches));
            recs.add(new Exercise(-1, "Russian twist", 53, "Russian twists are a dynamic core exercise that targets the obliques and engages the entire abdominal region. To perform Russian twists, sit on the floor with your knees bent, leaning back slightly to engage your core. Hold a weight or medicine ball with both hands, and lift your feet off the ground, balancing on your sit bones. Rotate your torso to one side, bringing the weight towards the floor beside you, and then twist to the other side. The movement mimics a twisting motion, challenging the oblique muscles and promoting core strength and stability. Maintaining a straight spine and controlling the movement are essential for effective execution and to minimize strain on the lower back.", R.drawable.russian_twist));

            // Aerobic exercises
            recs.add(new Exercise(-1, "Running", 71, "Running is a highly accessible and invigorating form of aerobic exercise that engages the entire body. It involves the rhythmic motion of swiftly moving forward, propelling oneself off the ground with each step. As a popular cardiovascular activity, running offers numerous physical and mental health benefits. It enhances cardiovascular endurance, strengthens muscles, and contributes to weight management. The rhythmic pounding of feet on the pavement or trail releases endorphins, promoting a sense of well-being and reducing stress. Whether pursued as a solo endeavor or enjoyed in a group, running provides an opportunity for self-reflection, goal-setting, and a tangible sense of accomplishment with each completed mile. With minimal equipment required, running is a versatile exercise that can be adapted to various fitness levels, making it an excellent choice for those seeking a simple yet effective way to improve overall health and fitness.", R.drawable.running));
            recs.add(new Exercise(-1, "Cycling", 72, "Cycling is an invigorating exercise that combines physical activity with exploration. Riding a bicycle provides a low-impact cardiovascular workout, strengthening muscles, particularly in the legs. It offers a sense of freedom and adventure, whether cruising city streets or tackling off-road trails. Beyond its fitness benefits, cycling is an eco-friendly mode of transportation and a social activity, fostering community through group rides. Whether for leisure, commuting, or sport, cycling promotes physical health, mental well-being, and a deeper connection with the environment.", R.drawable.cycling));
            recs.add(new Exercise(-1, "Jumping rope", 73, "Jumping rope is a dynamic and efficient cardiovascular exercise that involves repeatedly jumping over a rapidly rotating rope. This simple yet effective workout engages multiple muscle groups, particularly the legs, core, and arms, improving overall fitness and coordination. It's a high-intensity, calorie-burning activity that can be adapted to various fitness levels. Jumping rope is not only a time-efficient way to enhance cardiovascular endurance but also aids in improving agility and balance. Portable and inexpensive, a jump rope is a convenient fitness tool, making it easy to incorporate into workouts at home or on the go. Whether used for warm-ups, interval training, or full workouts, jumping rope is a versatile and enjoyable exercise that offers a quick and effective path to better health.", R.drawable.jumping_rope));
            recs.add(new Exercise(-1, "Swimming", 74, "Swimming is a low-impact, full-body workout that engages muscles, improves cardiovascular health, and enhances flexibility. The buoyancy of water reduces joint stress, making it suitable for all fitness levels. This exercise promotes muscle toning, lung capacity, and stress relief, offering a refreshing and versatile way to stay fit.", R.drawable.swimming));


            return recs;

    }


}
